export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_NOTIFICATION = 'AUTH_NOTIFICATION';

export const AUTH_OTHER_SUCCESS = 'AUTH_OTHER_SUCCESS';
export const AUTH_OTHER_LOGOUT = 'AUTH_OTHER_LOGOUT';

export const FETCH_MEMBERS_START = 'FETCH_MEMBERS_START';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_ERROR = 'FETCH_MEMBERS_ERROR';

export const FETCH_MEMBERS_DELETE_SUCCESS = 'FETCH_MEMBERS_DELETE_SUCCESS';
export const FETCH_MEMBERS_DELETE_FINISH = 'FETCH_MEMBERS_DELETE_FINISH';

export const FETCH_MEMBER_CHANGE_INDEX = 'FETCH_MEMBER_CHANGE_INDEX';

export const STATUS_THE_PAGE_CHART = 'STATUS_THE_PAGE_CHART';
export const STATUS_THE_PAGE_MEMBER = 'STATUS_THE_PAGE_MEMBER';
export const STATUS_THE_PAGE_TASK = 'STATUS_THE_PAGE_TASK';
export const STATUS_THE_PAGE_TRACK = 'STATUS_THE_PAGE_TRACK';
