export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_NOTIFICATION = 'AUTH_NOTIFICATION';

export const FETCH_MEMBERS_START = 'FETCH_MEMBERS_START';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_ERROR = 'FETCH_MEMBERS_ERROR';

export const FETCH_MEMBERS_DELETE_SUCCESS = 'FETCH_MEMBERS_DELETE_SUCCESS';
export const FETCH_MEMBERS_DELETE_FINISH = 'FETCH_MEMBERS_DELETE_FINISH';
